---
title: "Simulation"
output: github_document
---

```{r}
library(tidyverse)
library(rvest)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## Simulations!!!

Here's our function from before.

```{r}
sim_mean_sd = function (n_obs, mu = 7, sigma = 4){
  
  x= rnorm(n= n_obs, mean= mu, sd= sigma)
  
  tibble(
  mu_hat= mean(x),
  sigma_hat = sd(x)
)
  
}
```

how did we use this before?
```{r}
sim_mean_sd(n_obs = 30)
```

How can we do this now?

Let's start with a for loop


```{r}
output = vector( "list", length = 100)

for(i in 1:100){
  
  output[[i]] = sim_mean_sd(n_obs =30)
}

bind_rows(output)
```
Let's use list columns instead.

```{r}
# expand_grid allow an input column to stay the same and keep track of all combinations of iteration and sample sizes
sim_results_df=
expand_grid(
  sample_size = 30,
  iteration = 1:100
) %>% 
  mutate(
    estimate_df = map(sample_size, sim_mean_sd)
  ) %>% 
  unnest(estimate_df)


```

```{r}
sim_results_df %>% 
  ggplot(aes(x= mu_hat))+geom_density()
```
!!! !!

What about changing sample size

I need an input list of changing sample sizes

```{r, cache=TRUE}
# cache will not keep track of changes happened before the chunk
# .x is a place holder, dont name your objects .x and .y
sim_results_df=
expand_grid(
  sample_size = c(30,60,120,240),
  true_sigma = c(6,3),
  iteration = 1:1000
)%>% 
  mutate(
    estimate_df = map2(.x= sample_size, .y= true_sigma, ~sim_mean_sd(n_obs = .x, sigma = .y))
  ) %>% 
  unnest(estimate_df)

```


```{r}
sim_results_df %>% 
  mutate(sample_size = str_c("N=", sample_size),
         sample_size = fct_inorder(sample_size)) %>% 
  ggplot(aes(x= sample_size, y= mu_hat))+geom_violin()+ facet_grid(. ~true_sigma)
```
```{r}
sim_results_df %>% 
  mutate(sample_size = str_c("N=", sample_size),
         sample_size = fct_inorder(sample_size)) %>% 
  group_by(sample_size) %>% 
  summarize(
    emp_st_err = sd(mu_hat)
  )
```

