---
title: "Writing functions"
output: github_document
---

```{r}
library(tidyverse)
library(rvest)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## z-scores！！

Let's compute z- score version of a list of numbers

```{r}
x_vec = rnorm(25, mean= 7, sd=4)

(x_vec - mean(x_vec))/sd(x_vec)
```

Suppose you want to do this often

```{r}
# z-scores = function(ARGUMENTS) {BODY OF MY FUNCTION}

z_scores = function(x) {
  if( !is.numeric(x)){
    stop("Z scores only work for numbers")
  }
  if (length(x) <3){
    stop("Z scores really work if you have three or more numbers")
  }
(x_vec - mean(x_vec))/sd(x_vec)
}
```


```{r}
z_scores (x= x_vec)
```


```{r}
z_scores(x = 1:10)
z_scores(rbinom(1000,1,.6))
z_scores(x=3)
```


## Let's have multiple outputs

Let's get the mean and sd from the vector input

```{r}
mean_and_sd = function(x){
  if( !is.numeric(x)){
    stop("Z scores only work for numbers")
  }
  if (length(x) <3){
    stop("Z scores really work if you have three or more numbers")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(
    mean = mean_x,
    sd = sd_x
  )
}

mean_and_sd(x_vec)
mean_and_sd(1:10)
mean_and_sd(rbinom(1000,1,.5))
```
## Let's start with simulations

```{r}
x_vec = rnorm(n=35, mean =7, sd= 4)

tibble(
  mean= mean(x_vec),
  sd = sd(x_vec)
)
```

can i do this using a function... YUP

```{r}
sim_mean_sd = function (n_obs, true_mean = 7, true_sd = 4){
  
  x= rnorm(n= n_obs, mean= true_mean, sd= true_sd)
  
  tibble(
  mean= mean(x),
  sd = sd(x)
)
  
}
```

does it work?

```{r}
sim_mean_sd(n_obs = 25, true_mean = 10, true_sd = 5)
```
## Fixing bad stuff

```{r}
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

dynamite_html = read_html(url)

review_titles = 
  dynamite_html %>%
  html_nodes(".a-text-bold span") %>%
  html_text()

review_stars = 
  dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-rating") %>%
  html_text() %>%
  str_extract("^\\d") %>%
  as.numeric()

review_text = 
  dynamite_html %>%
  html_nodes(".review-text-content span") %>%
  html_text() %>% 
  str_replace_all("\n", "") %>% 
  str_trim()

reviews = tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
)
```

Let's write a function to get reviews

```{r}
read_page_reviews = function(url){
  
  dynamite_html = read_html(url)

review_titles = 
  dynamite_html %>%
  html_nodes(".a-text-bold span") %>%
  html_text()

review_stars = 
  dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-rating") %>%
  html_text() %>%
  str_extract("^\\d") %>%
  as.numeric()

review_text = 
  dynamite_html %>%
  html_nodes(".review-text-content span") %>%
  html_text() %>% 
  str_replace_all("\n", "") %>% 
  str_trim() %>% 
  str_subset("The media could not be loaded.", negate = TRUE) %>% 
    str_subset("^$", negate = TRUE)

reviews = 
  tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
)

reviews
  
}
```

Let's try with a url

```{r}

url="https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"
read_page_reviews(url)

```

What good does this do?

```{r}
base_url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber="

vec_url= str_c(base_url, c(1,2,3,4,5))

dynamite_reviews = bind_rows(
  
  read_page_reviews(vec_url[1]),
  read_page_reviews(vec_url[2]),
  read_page_reviews(vec_url[3]),
  read_page_reviews(vec_url[4]),
  read_page_reviews(vec_url[5])
)

dynamite_reviews
```





